version: "3.8"

services:
  db_aliare:
    image: postgres
    container_name: db_aliare
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=desafio_aliare
      - POSTGRES_PASSWORD=aliare
      - POSTGRES_DB=db_aliare
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: aliare
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - db_aliare
    depends_on:
      - db_aliare

volumes:
  pgdata:
    driver: local

networks:
  api: